### PR TITLE
Add option to force reload app on logout

### PR DESCRIPTION
**Pull request by michael-dewar**
Add an option to force reload the app on logout.

### CODE REVIEW

**Comment by michael-dewar** [comment]
@nicholaelaw you can try if this meets your needs.

**Comment by PaulC91** [comment]
Nice job. I wasn't sure if a session reload would work from inside a module but it looks like it does!

Can you add yourself as a contributor in the description file before I merge?

**Comment by michael-dewar** [comment]
Done.  Thanks!

**Comment by nicholaelaw** [comment]
Sorry I haven't been able to respond earlier. This works flawlessly. No UI flashing at all. Thank you very much!

**Pull request merged**
